export const langText = [
  {
    id: 0,
    apiLang: navigator.language,
    search: "Search",
    searchTitles: "Search title...",
    movie: "movies",
    tv: "tv series",
    sorting: "A - Z",
    releaseDate: "Release Date: ",
    popularity: "Popularity: ",
    voteCount: "Vote Count: ",
    voteAverage: "Vote Average: ",
    genres: "Genres: ",
    productionCountries: "Production Countries: ",
    productionCompanies: "Production Companies: ",
    runTime: "Run Time: ",
    episodesNumber: "Number of Episodes: ",
    seasonsNumber: "Number of Seasons: ",
    status: "Status: ",
    moreLoad: "Scroll to load more...",
    noMoreLoad: "There is nothing more to load...",
    welcome: "Start typing, choose what you want to search for and click Search or press Enter...",
    imdb: "Click!"
  },

  {
    id: 1,
    apiLang: "pl-PL",
    search: "Szukaj",
    searchTitles: "Szukaj tytułów...",
    movie: "filmy",
    tv: "seriale",
    sorting: "A - Z",
    releaseDate: "Data premiery: ",
    popularity: "Popularność: ",
    voteCount: "Ilość głosów: ",
    voteAverage: "Średnia głosów: ",
    genres: "Gatunek: ",
    productionCountries: "Kraj produkcji: ",
    productionCompanies: "Studia produkcyjne: ",
    runTime: "Czas trwania: ",
    episodesNumber: "Odcinków: ",
    seasonsNumber: "Sezonów: ",
    status: "Status: ",
    moreLoad: "Przewiń, aby załadować więcej ...",
    noMoreLoad: "Brak wyników...",
    welcome: "Wpisz czego szukasz, wybierz czy szukać wśród filmów lub seriali, a następnie kliknij Szukaj lub wciśnij Enter...",
    imdb: "Kliknij!"
  },

  {
    id: 2,
    apiLang: "de-DE",
    search: "Suche",
    searchTitles: "Suche titel...",
    movie: "Filme",
    tv: "TV-Serie",
    sorting: "A - Z",
    releaseDate: "Veröffentlichungsdatum: ",
    popularity: "Popularität: ",
    voteCount: "Anzahl der Stimmen: ",
    voteAverage: "Durchschnittliche Stimmen: ",
    genres: "Filmgenre: ",
    productionCountries: "Produktionsland: ",
    productionCompanies: "Produktionsstudios: ",
    runTime: "Spielzeit: ",
    episodesNumber: "Folge: ",
    seasonsNumber: "Staffel: ",
    status: "Status: ",
    moreLoad: "Scrollen, um mehr zu laden ...",
    noMoreLoad: "Es gibt nichts mehr zu laden ...",
    welcome: "Starten Sie die Eingabe, wählen Sie, was Sie suchen möchten, und klicken Sie auf Suchen oder drücken Sie die Eingabetaste...",
    imdb: "Klicken!"
  },

  {
    id: 3,
    apiLang: "es-ES",
    search: "",
    searchTitles: "",
    movie: "",
    tv: "",
    sorting: "A - Z",
    releaseDate: "",
    popularity: "",
    voteCount: "",
    voteAverage: "",
    genres: "",
    productionCountries: "",
    productionCompanies: "",
    runTime: "",
    episodesNumber: "",
    seasonsNumber: "",
    status: "",
    moreLoad: "",
    noMoreLoad: "",
    imdb: ""
  }
]
